services:

  testrunner:
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
    depends_on:
      dominant:
        condition: service_healthy
    volumes:
      - .:$PWD
    working_dir: $PWD
    command: /sbin/init

  dominant:
    image: ghcr.io/valitydev/dominant-v2:master
    command: /opt/dmt/bin/dmt foreground
    healthcheck:
      test: "/opt/dmt/bin/dmt ping"
      interval: 5s
      timeout: 3s
      retries: 12

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dmt
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
